app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from Vitamins.views import PageNotFoundErrorView, ServerErrorView
from .sitemaps import ProductSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'products': ProductSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('Vitamins.urls')),
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="Seo_things/robots.txt", content_type='text/plain')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )
]

handler404 = PageNotFoundErrorView.as_view()
handler500 = ServerErrorView.as_view()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vitamins/models.py
from django.utils.text import slugify
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

from unidecode import unidecode


STATUS_CHOICE = (
    ('process', 'В процессе'),
    ('shipped', 'Отправлено'),
    ('Delivered', 'Доставлено'),
)


RATING = (
    (1, '★☆☆☆☆'),
    (2, '★★☆☆☆'),
    (3, '★★★☆☆'),
    (4, '★★★★☆'),
    (5, '★★★★★'),
)


class Category(models.Model):
    name = models.CharField('Название', max_length=120)
    slug = models.SlugField('Слаг', unique=True, db_index=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Категории'


class Vendor(models.Model):
    name = models.CharField('Название', max_length=120)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Производитель'



class Product(models.Model):
    categories = models.ForeignKey( Category, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, help_text='Указывать не обяз \
                                                                                 ательно, это просто задел на будущее!')

    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    old_price = models.DecimalField('Старая цена', max_digits=10, decimal_places=2, null=True, blank=True, help_text='Указ\
                                            ывать в том случае если хотите сделать скидку')

    image = models.ImageField('Изображение', upload_to='vitamins/')
    title = models.CharField('Название продукта', max_length=120)
    description = models.TextField('Описание', null=True, blank=True)
    dateCreation = models.DateTimeField('Дата создания', auto_now_add=True)
    updated = models.DateTimeField('Дата обновления', null=True, blank=True)
    slug = models.SlugField('Слаг', unique=True, db_index=True)
    specifications = models.TextField('Состав')
    release_form = models.CharField('Форма выпуска', max_length=120, null=True)
    age = models.PositiveSmallIntegerField('Возраст', null=True)
    country = models.CharField('Страна производитель', max_length=120, null=True)
    is_available = models.BooleanField('В наличии', default=True)
    status = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)
    quantity = models.PositiveIntegerField('Количество', default=1, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product_details', kwargs={'slug': self.slug})


    class Meta:
        ordering = ['dateCreation']
        verbose_name_plural = 'Добавление продукта'

    def get_percentage(self):
        new_price = (self.price / self.old_price) * 100
        return new_price

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    images = models.ImageField(upload_to='product_images/')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Кратинки к продукту'


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    body = models.TextField()
    commentator = models.ForeignKey(User, on_delete=models.CASCADE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(choices=RATING, default=None)

    class Meta:
        verbose_name_plural = 'Комментарии к продукту'

    def __str__(self):
        return self.product.title

    def get_rating(self):
        return self.rating


class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField('Имя', max_length=50)
    last_name = models.CharField('Фамилия', max_length=50)
    email = models.EmailField('Email')
    address = models.CharField('Адрес', max_length=250)
    postal_code = models.CharField('Почтовый индекс', max_length=20)
    city = models.CharField('Город', max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField('Статус платежа', default=False)
    phone_number = models.BigIntegerField('Номер телефона')
    track_number = models.CharField('Трекномер', max_length=120, null=True, blank=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'{self.first_name}-{self.last_name}'

    def get_total_cost(self):
        orderitems = self.cartorderitem_set.all()
        total = sum([item.get_cost() for item in orderitems])
        return total

    def get_cart_item(self):
        orderitems = self.cartorderitem_set.all()
        total = sum([item.qty() for item in orderitems])
        return total


class CartOrderItem(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField('Количество', default=1)
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)

    def get_cost(self):
        return self.price * self.qty

templates/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}О нас{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col">
            <h1 class="">Кто мы и что мы?</h1>
            <p class="mt-5">
               <strong>Наша миссия</strong>: Мы - команда,заинтересовынные в улучшении качества вашего здоровья.
                Наша миссия - сделать доступными качественные витамины и пищевые добавки из Турции для всех.
                <strong>Качество превыше всего</strong>: Мы стремимся предоставить вам качественную продукцию.
                Для многих не секрет что витамины из Турции натуральные и проходят строгую проверку.
                <strong>Доступность</strong>: Мы верим, что забота о здоровье должна быть доступной каждому.
                Поэтому мы предлагаем конкурентоспособные цены.Наши услуги: Импорт и продажа добротных витаминов из Турции.
                Возможна доставка по всей России. Свяжитесь с нами Если у вас есть какие-либо вопросы или вам нужна
                дополнительная информация, не стесняйтесь обращаться к нам. Мы всегда готовы помочь вам заботиться о своем здоровье.
               </p>
            <a class="float-end btn btn-outline-dark" href="{% url 'main' %}">Продолжить шоппинг</a>
            <div class="messangers mt-4">
                <a href="https://wa.me/79196281443"><i style="color: #25D366;" class="fa-brands fa-whatsapp fa-2xl"></i></a>
                <a class="ms-3"  href="https://www.instagram.com/i_apaika/?utm_source=qr&igshid=YzU1NGVlODEzOA%3D%3D">
                    <i style="color: rgb(228, 64, 95);" class="fa-brands fa-instagram fa-2xl"></i></a>
            </div>

        </div>
        <div class="col-sm">
            <img class="mt-5 ms-5 about-us-img" src="{% static 'img/02-Vitamins-All-Truth.jpg' %}" alt="">
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" property="og:description" content="Витамины из Турции не значит дорого. Добро пожаловать в наш магазин!">
    <meta property="og:image" content="https://img.freepik.com/free-vector/essential-vitamin-and-mineral-complex_52683-35723.jpg?w=1380&t=st=1694964704~exp=1694965304~hmac=926d57fbd7f2d722529d8c76eac9a2dd695bc280da62a577c6669745be40e9bb">
    <meta name="description" content="Купите витамины в Казани по выгодным ценам. Большой выбор витаминов для здоровья и энергии.">
    <meta name="description" content="Качественные витамины из Турции. Полезные добавки для поддержания вашего здоровья. Закажите витамины из Турции прямо сейчас.">
    <meta name="description" content="Найдите витамины по хорошей цене в нашем магазине. Большой выбор доступных вариантов для укрепления вашего здоровья.">
    <meta name="keywords" content="Витамины, Казань, Здоровье, Аптека, Купить, Выгодные цены, Добавки">
    <meta name="keywords" content="Витамины, Турция, Зарубежные, Качество, Купить, Выгодные цены, Полезные добавки, Поддержка здоровья, Заказать">
    <meta name="keywords" content="Витамины, Цена, Здоровье, Доступный выбор, Покупка, Скидки, Акции">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load compress %}
    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    {% endcompress %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link rel="icon" href="{% static 'img/vitamin-c.png' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>{% block title %}Витамины в Казани{% endblock %}</title>
</head>
<body>

{% block header %}
        <header>
            <nav class="main-pg navbar navbar-expand-lg navbar-light">
                <div class="container">
                    <a href="{% url 'main' %}" class="navbar-brand">X-YRO 2005</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                        aria-controls="navbarContent" aria-expanded="false">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarContent">
                        <ul class="navbar-nav ms-auto mb-2">
                            {% if request.user.is_superuser %}
                            <li class="nav-item">
                                <a href="{% url 'chart' %}" class="nav-link">Таблица</a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a href="{% url 'main' %}" class="nav-link">Домашняя</a>
                            </li>
                        <li class="nav-item dropdown">
                        <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Категории
                                  </a>
                                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                      {% for category in categories %}
                                            <li><a class="dropdown-item" href="{% url 'category_products' category.slug %}">{{ category.name }}</a></li>
                                      {% endfor %}
                                  </ul>
                                </li>
                            <li class="nav-item">
                                <a href="{% url 'about_us' %}" class="nav-link">О нас</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://t.me/xyro2005" class="nav-link">Сайты на заказ</a>
                            </li>

                            <form action="{% url 'search_results' %}" method="get">
                                <div class="search">
                                <div class="icon"></div>
                                    <div class="input">
                                        <input name="title" type="text"  placeholder="Поиск" id="mySearch">
                                    </div>
                                    <span class="clear"></span>
                            </div>
                            </form>
                        </ul>
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if request.user.is_authenticated %}
                            <form method="post" action="{% url 'account_logout' %}">
                              {% csrf_token %}
                              {% if redirect_field_value %}
                              <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                              {% endif %}

                                <a href="{% url 'user_orders' %}">{{ user.username }}</a> | <button class="me-2 nav-item sign-out" type="submit">Выход</button>
                                <a style="color: black;" href="{% url 'cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i></a>
                            </form>
                        {% else %}
                          <li class="nav-but">
                            <a href="{% url 'account_login'%}" class="me-1 btn btn-outline-dark">Войти</a>
                            <a href="{% url 'account_signup' %}" class="me-2 btn btn-outline-dark">Регистрация</a>
                            <a style="color: black;" href="{% url 'cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i></a>
                          </li>
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
{% endblock %}

{% block content %}{% endblock %}

{% compress js %}
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/prod_details.js' %}"></script>
<script src="{% static 'js/modal.js' %}"></script>
{% endcompress %}
<script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],

            offset: 'bottom-in-view',

            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function () {
                $('.loading').hide();
            }

        });
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load cache %}


{% block content %}
{% cache 300 index request.user.username page_obj %}
<div class="container">
    <div class="row infinite-container">
        {% for product in products %}
        <div class="col-md-3 infinite-item">
            <div class="product-box mt-5">
                <div class="product-inner-box position-relative">
                    <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="image-fluid" alt=""></a>
                    {% if product.is_available %}
                    <form action="{% url 'cart_add' product.slug %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form.update }}
                        <div style="display: none;">{{ cart_product_form.quantity }}</div>
                        <div class="cart-btn">
                            <button class="btn bg-white shadow-sm rounded-pill">Добавить в корзину</button>
                        </div>
                    </form>
                    {% else %}
                    <div class="cart-btn">
                        <button disabled class="btn bg-white shadow-sm rounded-pill">Добавить в корзину</button>
                    </div>
                    {% endif %}
                    <div class="product-info">
                        <div class="product_name">
                            <h3>{{ product.title }}</h3>
                        </div>
                        <div class="product-price">
                            ₽<span>{{ product.price }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% include 'infinite_scroll.html' %}
</div>
{% endcache %}
{% endblock %}

templates/infinite_scroll.html
<div class="row">
    <div class="col-12">
        {% if page_obj.has_next %}
        <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
        {% endif %}
    </div>
</div>

templates/product_details.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
<div class="container">
    {% cache 300 details request.user.username product.slug %}
    <div class="row product-main-info mt-3 pt-5 pb-5 ">
        <div class="col-sm-3 img-container">
            <img class="product-detail-img" src="{{ product.image.url }}" alt="">
        </div>
        <div class="col-sm-4 mt-5">
            <h1 class="searched-title">{{ product.title }}</h1>

            <div class="main-information mt-5">
                {% if product.is_available %}
                <p>Статус:&nbsp;<strong>В наличии</strong></p>
                {% else %}
                <p>Статус:&nbsp;<strong>Нет наличии</strong></p>
                {% endif %}
                <p>Осталось:&nbsp;<strong>{{ product.quantity }} шт.</strong></p>
                <p>Производитель:&nbsp;<strong> {{ product.vendor }}</strong></p>
                <p>Форма выпуска:&nbsp;<strong> {{ product.release_form }}</strong></p>
                <p>Возраст от:&nbsp;<strong> {{ product.age }}+</strong></p>
                <p>Страна выпуска:&nbsp;<strong> {{ product.country }}</strong></p>
            </div>
        </div>
        <div class="col-sm-3 ">
            <div class="price mt-5">
                {% if product.old_price %}
                    <p>Цена:</p>
                    <p><s>{{ product.old_price }} ₽</s></p>
                    <strong>{{ product.price }} ₽ - {{ product.get_percentage|floatformat:"0"  }} %</strong>
                {% else %}
                    <strong>{{ product.price }} ₽ </strong>
                {% endif %}
                <hr>
                <div class="mt-3 d-grid gap-2">
                    {% if product.is_available %}
                    <form action="{% url 'cart_add' product.slug %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form.update }}
                        <div style="display: none;">{{ cart_product_form.quantity }}</div>
                        <div class="mt-3 d-grid gap-2">
                            <button class="btn btn-success">Добавить в корзину</button>
                        </div>
                    </form>
                    {% else %}
                    <div class="mt-3 d-grid gap-2">
                        <button disabled class="btn btn-success">Добавить в корзину</button>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endcache %}
    <div class="row product-main-info pt-5 pb-5 mt-5 ">
        <div class="col-sm">
            <button id="descr-btn" class="btn btn-outline-dark ms-2">Описание</button>
            <button id="specifications-btn" class="btn btn-outline-dark ms-2 me-2">Состав</button>
            <button id="comments-btn" class="btn btn-outline-dark">Комментарии</button>
            <div id="descr-block" class="product-descr mt-5 ms-5">
                <p>{{ product.description }}</p>
            </div>
            <div id="struc-block" class="product-struc mt-5 ms-5" style="display: none;">
                <h3>Состав:</h3>
                <div><p>{{ product.specifications|linebreaks }}</p></div>
            </div>
            <div id="comments-block" class="product-comments mt-5 ms-5 infinite-container" style="display: none;">
                {% if user.is_authenticated %}
                <form action="{% url 'add_comment' product.slug %}" method="post">
                {% csrf_token %}
                    <textarea class="form-control" name="body" id="" cols="30" rows="10"></textarea>
                    <div class=" mt-3">{{ comment_form.rating }}</div>
                    <button type="submit" class="mt-3 btn btn-primary">Добавить комментарий</button>
                </form>
                {% else %}
                Пожалуйста <a href="{% url 'account_login'%}">войдите</a> чтобы добавить комментарий...
                {% endif %}
                <div class="product-rating mt-5">
                    {% if avg_rating.rating %}
                    <h5>Средний балл: {{ avg_rating.rating|floatformat }} из 5.0</h5>
                    {% else %}
                    <h5>Средний балл: 0 из 5.0, так как оценок еще нет</h5>
                    {% endif %}

                </div>
                <div class="pb-5 infinite-item">
                    {% for comment in comments %}

                    <div class="">
                      <div class="comment-header mt-4 mb-3">commentator · <strong style="color: #000000;">{{ comment.commentator }}</strong> | date · <strong style="color: #000000;">{{ comment.dateCreation}} {{ comment.get_rating_display }}</strong></div>
                      <p class="">{{ comment.body }}</p>
                    </div>


                    {% endfor %}
                    <div class="col-12">
                        {% if comments.has_next %}
                        <a class="infinite-more-link" href="?page={{ comments.next_page_number }}"></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/products_by_categories.html
{% extends 'base.html' %}

{% block title %}
    {% for category in categories %}
    {{ category.name }}
    {% endfor %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row infinite-container">
        {% for product in products %}
        <div class="col-md-3 infinite-item">
            <div class="product-box mt-5">
            <div class="product-inner-box position-relative">
                <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="image-fluid" alt=""></a>
                {% if product.is_available %}
                    <form action="{% url 'cart_add' product.slug %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form.update }}
                        <div style="display: none;">{{ cart_product_form.quantity }}</div>
                        <div class="cart-btn">
                            <button class="btn bg-white shadow-sm rounded-pill">Добавить в корзину</button>
                        </div>
                    </form>
                    {% else %}
                    <div class="cart-btn">
                        <button disabled class="btn bg-white shadow-sm rounded-pill">Добавить в корзину</button>
                    </div>
                    {% endif %}
                <div class="product-info">
                    <div class="product_name">
                        <h3>{{ product.title }}</h3>
                    </div>
                    <div class="product-price">
                        ₽<span>{{ product.price }}</span>
                    </div>
                </div>
            </div>

            </div>
        </div>
        {% endfor %}
    </div>
    {% include 'infinite_scroll.html' %}
</div>
{% endblock %}

templates/search_product.html
{% extends 'base.html' %}

{% block title %}Поиск{% endblock %}

{% block content %}
<div class="container">
    {% if products %}
    <div class="row mt-5 infinite-container">
        {% for product in products %}
        <div class="col-sm-2 mb-3 infinite-item">
            <div class="searched-product-img">
                <a href="{{ product.get_absolute_url }}"><img class="searched-img" src="{{ product.image.url }}" alt=""></a>
            </div>
        </div>
        <div class="col-sm-7 infinite-item">
            <h3 class="searched-title mt-4">{{ product.title }}</h3>
            <div class="main-information mt-3">
                {% if product.is_available %}
                <p>Статус:&nbsp;<strong>В наличии</strong></p>
                {% else %}
                <p>Статус:&nbsp;<strong>Нет наличии</strong></p>
                {% endif %}
                <p>Производитель:&nbsp;<strong> {{ product.vendor }}</strong></p>
                <p>Форма выпуска::&nbsp;<strong> {{ product.release_form }}</strong></p>
                <p>Возраст от:&nbsp;<strong> {{ product.age }}+</strong></p>
            </div>
        </div>
        <div class="col-sm-2 infinite-item">
            <div class="price mt-5">
                {% if product.old_price %}

                    <p><s>{{ product.old_price }} ₽</s></p>
                    <strong>{{ product.price }} ₽  &nbsp; - {{ product.get_percentage|floatformat:"0"  }} % </strong>
                {% else %}
                    <strong>{{ product.price }} ₽</strong>
                {% endif %}
                <hr>
                {% if product.is_available %}
                    <form action="{% url 'cart_add' product.slug %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form.update }}
                        <div style="display: none;">{{ cart_product_form.quantity }}</div>
                        <div class="mt-3 d-grid gap-2">
                            <button class="btn btn-success">Добавить в корзину</button>
                        </div>
                    </form>
                {% else %}
                <div class="mt-3 d-grid gap-2">
                    <button disabled class="btn btn-success">Добавить в корзину</button>
                </div>
                {% endif %}
            </div>
        </div>
        <hr class="searched-hr">
            {% endfor %}
    </div>
        <div class="row">
        <div class="col-12">
            {% if page_obj.has_next %}
            <a class="infinite-more-link" href="?{{ search_params }}&page={{ page_obj.next_page_number }}"></a>
            {% endif %}
        </div>
    </div>
    {% else %}
    <h1 class="text-center mt-5">Витаминов по вашему запросу не найдено...</h1>
    {% endif %}
</div>

{% endblock %}

templates/user_orders.html
{% extends 'base.html' %}

{% block title %}Последние платежи{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="table-responsive">
            <h1 class="text-center mb-5">Последние 3 платежа</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>Имя</th>
                        <th>Сумма</th>
                        <th>Статус платежа</th>
                        <th>Трек номер</th>
                    </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>
                            {% for item in order.cartorderitem_set.all %}
                            <p>{{ item.product.title }} х{{ item.qty }}</p>
                            {% endfor %}
                        </td>
                        <td>
                            {% for item in order.cartorderitem_set.all %}
                                <p>{{ item.get_cost }}</p>
                            {% endfor %}
                        </td>
                        <td>
                            {% if order.paid %}
                            <i class=" fa-solid fa-circle-check fa-lg" style="color: #48b71f;"></i>
                            {% else %}
                            <i class=" fa-solid fa-circle-xmark fa-lg" style="color: #cd2a18;"></i>
                            {% endif %}
                        </td>
                        <td>
                            {% if order.track_number %}
                            <p>{{ order.track_number }}</p>
                            {% elif order.paid == False %}
                            <p>Вы не заплатили за заказ</p>
                            {% else %}
                            <p>Скоро здесь появится <br>
                                трек номер</p>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}